// -*- C++ -*- generated by wxGlade 0.5 on Tue May 29 00:24:38 2007 from Z:\WIP\CookTimer\CookTimer.wxg

#include <wx/wx.h>
#include "CookTimerFrame.h"

class CookTimer: public wxApp
	{
	public:
		bool OnInit();
	};

IMPLEMENT_APP(CookTimer)

bool CookTimer::OnInit()
	{
	CookTimerFrame *mainFrame = new CookTimerFrame(NULL);
	mainFrame->Show();
	return true;
	}
